USE customer_behavoir;

/*verifying data in customer table
select top 10 *
from customer;
*/

/*Q1. What is total revenue generated by male vs female customer */
select gender, SUM(purchase_amount) AS TotalRevenue
from customer
group by gender;


/*Q2 Which customers used a discount but still spent more than avg purchase amount? */
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' AND purchase_amount >= (select AVG(purchase_amount)
                                                      from customer);


/*Q3 Which are top 5 products with highest avg review rating?  These products can be sold at higher/premium price */

select top 5 item_purchased, ROUND(AVG(review_rating),2) AS AvgRating
from customer
group by item_purchased
order by AvgRating DESC;


/*Q4 Compare avg purchase amount between standard and Express Shipping */

select shipping_type, AVG(purchase_amount) AS "Avg Purchase Amount"
from customer
where shipping_type IN ('Express','Standard')
group by shipping_type;


/*Q5 Do subscribed customer spend more? Compare avg spend and total revenue between sub and non subs.  Helps to determine subscription model is doing good or no */

select subscription_status AS "Subcription Status",COUNT(customer_id) AS "Total Customers",AVG(purchase_amount) AS "Average Spend",SUM(purchase_amount) AS "Total Revenue"
from customer
group by subscription_status
order by SUM(purchase_amount) DESC;


/*Q6 Which 5 products have highest percentage of purchase with discount applied */
select TOP 5 item_purchased,
100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*) AS "DiscountRate"
from customer
group by item_purchased
order by DiscountRate DESC;


/*Q7 Segment customers into New, Returning and Loyal based on total no of purchases, and show count of each segment (Using CTE) */

with customer_type as (
select customer_id, previous_purchases,
(CASE WHEN previous_purchases <=1 THEN 'New' WHEN previous_purchases <=10 THEN 'Returning' ELSE 'Loyal' END) AS cust_type
from customer)

select cust_type AS "Customer Type", count(*) AS "No of Customers"
from customer_type
group by cust_type
order by [No of Customers] DESC;


/*Q8 What are top 3 Most purchased product within each category?  (used CTE along with WINDOW function of ROW_Number()) */

with item_counts as (
select category, 
item_purchased,
count(customer_id) as "No of Orders",
row_number() over (partition by category order by count(customer_id) desc) as "item_rank"
from customer
group by category,item_purchased
)

select item_rank,category,item_purchased
from item_counts
where item_rank<=3;



/*Q9 Are customers who are repeat buyers (more than 5 purchases) also likely to subscribe? */
select subscription_status,
count(customer_id) AS "repeat buyers"
from customer
where previous_purchases > 5
group by subscription_status;



/*Q10 What is the revenue contribution by Age group? */
select age_group,
SUM(purchase_amount) AS "Total Revenue"
from customer
group by age_group
order by [Total Revenue] DESC;


